<a href="https://colab.research.google.com/github/dickynainggolan/Pemograman-Dasar/blob/main/ATS_PRATIKUM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ATS PEMOGRAMAN DASAR

KELOMPOK 6

Anggota Kelompok:
1. Seraf David Simanungkalit 4232401053
2. Dicky Nainggolan 4232401047
3. Anggun Caroline 4232401037

In [ ]:
#. 1.Percabangan / Branching

suhu = float(input("Masukkan suhu air pendingin (°C): "))

if suhu <= 90:
    print("STATUS: Normal")
elif 90 < suhu < 100:
    print("STATUS: Warning")
else:  # suhu >= 100
    print("ALERT: SHUTDOWN")


Masukkan suhu air pendingin (°C): 120
ALERT: SHUTDOWN


# Penjelasan

# 1. Input Suhu
- suhu = float(input("Masukkan suhu air pendingin (°C): "))

Kode ini meminta pengguna untuk memasukkan nilai suhu (dalam Celsius). Input tersebut kemudian diubah menjadi tipe data float (bilangan desimal) dan disimpan dalam variabel suhu.

# 2. Pengecekan Kondisi (Percabangan):
- if suhu <= 90:

Jika suhu 90°C atau kurang, cetak "STATUS: Normal".

- elif 90 < suhu < 100:

Jika suhu lebih dari 90°C DAN kurang dari 100°C, cetak "STATUS: Warning". Kondisi ini diperiksa hanya jika kondisi if sebelumnya salah.

- else:

Untuk semua kondisi lainnya (yaitu, suhu 100°C atau lebih), cetak "ALERT: SHUTDOWN". Blok else ini dijalankan jika semua kondisi sebelumnya (if dan elif) salah.

In [ ]:
# 3. Looping for

vibrasi_mesin = [1.2, 0.9, 2.5, 3.1, 1.8]

for i in range(len(vibrasi_mesin)):
    if vibrasi_mesin[i] > 2.0:
        print(f"Warning: Unit {i+1} vibrasi tinggi!")


# Penjelasan

# 1. Data Vibrasi
- vibrasi_mesin = [1.2, 0.9, 2.5, 3.1, 1.8]               

Ini adalah daftar (list) yang menyimpan nilai-nilai getaran dari 5 unit mesin.

# 2. Perulangan (Loop)
- for i in range(len(vibrasi_mesin)):         

Instruksi ini memulai perulangan. Fungsi range(len(vibrasi_mesin)) menghasilkan angka urut (index) dari 0 hingga 4 (sesuai dengan jumlah unit). Variabel i akan mengambil nilai indeks ini secara bergantian.

# 3. Pengecekan Kondisi
- if vibrasi_mesin[i] > 2.0:   

Di dalam loop, setiap nilai vibrasi diperiksa satu per satu. vibrasi_mesin[i] merujuk pada nilai vibrasi unit ke-i. Kondisi ini memeriksa apakah nilai tersebut melebihi ambang batas 2.0

# 4. Output Peringatan
- print(f"Warning: Unit {i+1} vibrasi tinggi!")

Jika kondisi di atas benar (vibrasi melebihi 2.0), kode akan mencetak pesan peringatan. Karena indeks i dimulai dari 0, digunakan i+1 agar nomor unit yang dicetak dimulai dari 1.

# Hasil yang Dihasilkan
Kode ini akan mencetak peringatan hanya untuk Unit 3 (nilai 2.5) dan Unit 4 (nilai 3.1).

Warning: Unit 3 vibrasi tinggi!         
Warning: Unit 4 vibrasi tinggi!

In [ ]:
# 5. Looping while

suhu_saat_ini = 60
target_suhu = 85

while suhu_saat_ini < target_suhu:
    print(f"Suhu saat ini: {suhu_saat_ini}°C")
    suhu_saat_ini += 5

Suhu saat ini: 60°C
Suhu saat ini: 65°C
Suhu saat ini: 70°C
Suhu saat ini: 75°C
Suhu saat ini: 80°C


# Penjelasan

# 1. Inisialisasi Nilai Awal
- suhu_saat_ini = 60:

Menentukan suhu awal sistem adalah 60°C.

- target_suhu = 85:

Menentukan batas suhu yang harus dicapai adalah 85°C.

# 2. Perulangan while
- while suhu_saat_ini < target_suhu:                    

Ini adalah inti dari perulangan. Kode di dalamnya akan terus dieksekusi selama kondisi ini benar, yaitu selama suhu_saat_ini masih di bawah 85.

# 3. Proses di Dalam Loop
- print(f"Suhu saat ini: {suhu_saat_ini}°C")             

Mencetak suhu yang sedang terjadi pada awal setiap langkah.

- suhu_saat_ini += 5:       

Ini adalah perintah kritis yang menaikkan suhu sebesar 5 derajat (simulasi pemanasan). Kenaikan ini memastikan bahwa suhu pada akhirnya akan mencapai (atau melampaui) target, sehingga perulangan dapat berhenti.

# Hasil yang Dihasilkan
Perulangan akan berhenti saat suhu mencapai 85 atau lebih. Outputnya akan terlihat seperti ini:                         
Suhu saat ini: 60°C          
Suhu saat ini: 65°C           
Suhu saat ini: 70°C          
Suhu saat ini: 75°C         
Suhu saat ini: 80°C

In [ ]:
# 7. Percabangan / Branching

kapasitas_maksimum = float(input("Masukkan kapasitas maksimum (Watt): "))
beban_terpakai = float(input("Masukkan beban terpakai (Watt): "))

persentase = (beban_terpakai / kapasitas_maksimum) * 100

if persentase <= 60:
    status = "Beban Ringan"
elif persentase <= 85:
    status = "Beban Sedang"
else:
    status = "Beban Berat"

print(f"Persentase pemakaian: {persentase:.2f}%")
print(f"Status Beban: {status}")

Masukkan kapasitas maksimum (Watt): 70
Masukkan beban terpakai (Watt): 50
Persentase pemakaian: 71.43%
Status Beban: Beban Sedang


# Penjelasan

# 1. Penerimaan Input dan Perhitungan Persentase

Input: Program meminta pengguna memasukkan dua nilai
- kapasitas_maksimum (misalnya, kapasitas gardu atau genset)
- beban_terpakai (beban yang sedang digunakan)

Perhitungan
- persentase = (beban_terpakai / kapasitas_maksimum) * 100

Kode ini menghitung persentase pemakaian dengan membagi beban terpakai dengan kapasitas maksimum, lalu dikalikan 100.

# 2. Penentuan Status (Percabangan)

Bagian ini menggunakan percabangan (if, elif, else) untuk menentukan status berdasarkan nilai persentase:

- if persentase <= 60:

Jika persentase <= 60%, statusnya adalah "Beban Ringan".

- elif persentase <= 85:

Kondisi ini hanya diperiksa jika kondisi sebelumnya (di atas) salah (artinya persentase sudah > 60%). Jika persentase <= 85%, statusnya adalah "Beban Sedang"

- else:

Ini adalah semua kondisi sisanya, yaitu jika persentase > 85%. Statusnya adalah "Beban Berat".

# 3. Output

Program menampilkan hasil perhitungan persentase (dibulatkan menjadi 2 angka di belakang koma) dan status beban yang telah diklasifikasikan.

In [ ]:
# 9. Looping + List

suhu_boiler = [92.5, 88.7, 95.1, 102.3, 97.8]

for suhu in suhu_boiler:
    print(f"Suhu: {suhu}°C", end="")
    if suhu > 100:
        print("  <- Peringatan: suhu di atas 100°C!")
    else:
        print()

Suhu: 92.5°C
Suhu: 88.7°C
Suhu: 95.1°C
Suhu: 102.3°C  <- Peringatan: suhu di atas 100°C!
Suhu: 97.8°C


# Penjelasan

# 1. Perulangan Data (Looping)

- for suhu in suhu_boiler:

Ini adalah perulangan for yang mengambil setiap nilai dari daftar suhu_boiler secara berurutan. Di setiap putaran, variabel suhu akan menyimpan nilai suhu saat itu (misalnya 92.5, lalu 88.7, dst.)

# 2. Output dan Format

- print(f"Suhu: {suhu}°C", end=""):
Mencetak nilai suhu saat ini. Penggunaan end="" sangat penting di sini, karena mencegah baris baru dibuat setelah mencetak suhu. Ini dilakukan agar pesan peringatan (jika ada) bisa dicetak di baris yang sama.

# 3. Pengecekan Kondisi

- if suhu > 100:: Program memeriksa apakah nilai suhu saat ini melebihi ambang batas 100°C.

Jika BENAR,
print(" <- Peringatan: suhu di atas 100°C!")
akan mencetak pesan peringatan, yang muncul tepat di samping nilai suhu.

Jika SALAH
(else), print() dijalankan. Ini hanya berfungsi untuk membuat baris baru, memastikan hasil pembacaan suhu berikutnya akan dicetak di baris yang terpisah.

In [1]:
# challenge Program: Simulasi Efisiensi Energi Pembangkit Listrik

# Fungsi untuk menghitung efisiensi (%)
def hitung_efisiensi(energi_masuk, energi_keluar):
    return (energi_keluar / energi_masuk) * 100

# Fungsi untuk menilai kategori efisiensi
def kategori_efisiensi(nilai):
    if nilai >= 80:
        return "Sangat Efisien"
    elif nilai >= 60:
        return "Cukup Efisien"
    else:
        return "Kurang Efisien"

print("=== SIMULASI EFISIENSI ENERGI PEMBANGKIT LISTRIK ===")
jumlah = int(input("Masukkan jumlah pembangkit yang akan dianalisis: "))

total_efisiensi = 0

# Perulangan for untuk setiap pembangkit
for i in range(jumlah):
    print(f"\nPembangkit ke-{i+1}")
    nama = input("Nama pembangkit: ")
    energi_masuk = float(input("Energi masuk (kJ): "))
    energi_keluar = float(input("Energi keluar (kJ): "))

    efisiensi = hitung_efisiensi(energi_masuk, energi_keluar)
    kategori = kategori_efisiensi(efisiensi)

    print(f"Efisiensi {nama}: {round(efisiensi, 2)}% → {kategori}")
    total_efisiensi += efisiensi

# Hitung rata-rata efisiensi
rata_rata = total_efisiensi / jumlah
print(f"\nRata-rata efisiensi seluruh pembangkit: {round(rata_rata, 2)}%")

# Perulangan while untuk simulasi tambahan
ulang = input("\nApakah ingin simulasi ulang? (y/n): ")
while ulang.lower() == "y":
    energi_masuk = float(input("Masukkan energi masuk (kJ): "))
    energi_keluar = float(input("Masukkan energi keluar (kJ): "))

    efisiensi = hitung_efisiensi(energi_masuk, energi_keluar)
    print(f"Hasil efisiensi: {round(efisiensi, 2)}% → {kategori_efisiensi(efisiensi)}")

    ulang = input("\nHitung lagi? (y/n): ")

print("\nTerima kasih telah menggunakan simulasi efisiensi energi!")


=== SIMULASI EFISIENSI ENERGI PEMBANGKIT LISTRIK ===
Masukkan jumlah pembangkit yang akan dianalisis: 3

Pembangkit ke-1
Nama pembangkit: PLTU Pernata
Energi masuk (kJ): 10000
Energi keluar (kJ): 7500
Efisiensi PLTU Pernata: 75.0% → Cukup Efisien

Pembangkit ke-2
Nama pembangkit: PLTG Rabayu
Energi masuk (kJ): 10000
Energi keluar (kJ): 8500
Efisiensi PLTG Rabayu: 85.0% → Sangat Efisien

Pembangkit ke-3
Nama pembangkit: PLTA Sejatra
Energi masuk (kJ): 10000
Energi keluar (kJ): 6500
Efisiensi PLTA Sejatra: 65.0% → Cukup Efisien

Rata-rata efisiensi seluruh pembangkit: 75.0%

Apakah ingin simulasi ulang? (y/n): n

Terima kasih telah menggunakan simulasi efisiensi energi!


Program ini digunakan untuk menghitung efisiensi pembangkit listrik, yaitu seberapa besar energi keluar dibanding energi masuk.
User memasukkan jumlah pembangkit.
Untuk setiap pembangkit, user memasukkan energi masuk dan energi keluar.
Program menghitung efisiensi dengan rumus:
efisiensi = (energi keluar / energi masuk) × 100
Hasilnya dikategorikan:
≥ 80% → Sangat Efisien
60–79% → Cukup Efisien
< 60% → Kurang Efisien
Program juga menampilkan rata-rata efisiensi semua pembangkit.
Terakhir, user bisa ulang simulasi dengan data baru.

